### ISSUE TITLE
titleタグが設定されていない

### ISSUE THREAD

**Issue by nobuchi** [CTRL-Infrastructure-team/ctrl_public_webpage#49]
各ページのtitleタグに文字が設定されていないため、タブの部分にURLが表示されます。
pagesディレクトリ内のvueファイルのscriptタグにhead(){...}と追加しようと思ってます。

参考：https://qiita.com/azujuuuuuun/items/7fe24cdb9c99b59a094a

**Comment by polyester-CTRL** [comment]
process.env.で記述した場合、サーバ上にある.envファイルの内容を読み取ります。このファイルはgitで管理されないので、ローカルで書き換えても反映されません。

ちなみにtitleは公開されるものなので、nuxt.config.jsに直書きしても大丈夫だと思います。そうできない理由があるのならば、書いてもらえると助かります。（ちゃんとした解決策を提示できると思うので）

**Comment by polyester-CTRL** [comment]
確かに謎ですね。（yarn2では[process.env.npm_package_~ の場合でも package.json から値を読み取らない仕様](https://github.com/yarnpkg/berry/issues/1659)に変わったみたいですが、ここで使っているのはyarn1でした……）

修正についてはお任せします！
