### ISSUE TITLE
フッターのメールアイコン

### ISSUE THREAD

**Issue by nobuchi** [CTRL-Infrastructure-team/ctrl_public_webpage#50]
クリックしても何も起こりません。
どのような機能があったのでしょうか？

**Comment by polyester-CTRL** [comment]
https://www.tohoho-web.com/how2/mail.htm
こちらの「mailto:」が使われています。
クリックすると指定されたメールアドレス宛でメールソフトが起動します。

もし表示されない場合は、ブラウザの設定を見直すかFirefoxなどを使うと表示されます。

**Comment by nobuchi** [comment]
ありがとうございます！

加えて質問したいのですが、こちらのアイコンに設定されているメールアドレスはCTRL11期のものでしょうか？
その場合、設定されたメールアドレスを tcu.ctrl@gmail.com に変更しても大丈夫でしょうか？

**Comment by polyester-CTRL** [comment]
確かそうだったと思います。自由に変更して構いません。
